# diagnostic_config.yaml - Конфигурация ML системы диагностики
ml_enabled: true
ml_settings:
  min_training_samples: 5  # Минимум багов для начала обучения (снижено для начала)
  retrain_frequency: 3     # Переобучать после каждых 3 новых багов
  confidence_threshold: 0.6  # Минимальная уверенность для предсказаний
  
  # Веса для различных признаков специфичных для календарной интеграции
  feature_weights:
    api_error_frequency: 2.5      # Частота ошибок API
    oauth_complexity: 2.0         # Сложность OAuth интеграции
    calendar_dual_mode: 1.8       # Режим двойного календаря
    conference_creation: 1.7      # Создание конференций
    service_account_usage: 1.5    # Использование Service Account
    cyclomatic_complexity: 1.2
    function_length: 1.0
    error_handling_ratio: 1.8     # Обработка ошибок
    historical_bug_frequency: 2.2
    
  # Настройки модели
  model_params:
    n_estimators: 50
    max_depth: 8
    min_samples_split: 3
    random_state: 42
    
  # Специальные категории багов для календарной системы
  bug_categories:
    - oauth_authentication_failure
    - service_account_permission_error
    - conference_creation_failure
    - dual_calendar_sync_issue
    - webhook_connection_timeout
    - api_rate_limiting
    - invalid_calendar_id
    - attendee_invitation_failure

# Настройки мониторинга
monitoring:
  log_analysis_enabled: true
  real_time_prediction: true
  auto_fix_suggestions: true
  risk_assessment: true
  
# Настройки безопасности
safety:
  auto_rollback: true
  test_before_apply: true
  backup_before_changes: true
  max_risk_tolerance: 0.3